#!/bin/bash
cat <<EOF > 0-iam_betty
#!/bin/bash
su betty
EOF
cat <<EOF > 1-who_am_i
#!/bin/bash
id -un
EOF
cat <<EOF > 2-groups
#!/bin/bash
groups
EOF
cat <<EOF > 3-new_owner
#!/bin/bash
chown betty hello
EOF
cat <<EOF > 4-empty
#!/bin/bash
touch hello
EOF
cat <<EOF > 5-execute
#!/bin/bash
chmod u+x hello
EOF
cat <<EOF > 6-multiple_permissions
#!/bin/bash
chmod u+x,g+x,o+r hello
EOF
cat <<EOF > 7-everybody
#!/bin/bash
chmod ugo+x hello
EOF
cat <<EOF > 8-James_Bond
#!/bin/bash
chmod 007 hello
EOF
cat <<EOF > 9-John_Doe
#!/bin/bash
chmod 753 hello
EOF
cat <<EOF > 10-mirror_permissions
#!/bin/bash
chmod --reference=olleh hello
EOF
cat <<EOF > 11-directories_permissions
#!/bin/bash
chmod -R ugo+X .
EOF
cat <<EOF > 12-directory_permissions
#!/bin/bash
mkdir -m 751 my_dir
EOF
cat <<EOF > 13-change_group
#!/bin/bash
chgrp school hello
EOF
cat <<EOF > 100-change_owner_and_group
#!/bin/bash
chown -hR vincent:staff .
EOF
cat <<EOF > 101-symbolic_link_permissions
#!/bin/bash
chown -h vincent:staff _hello
EOF
cat <<EOF > 102-if_only
#!/bin/bash
chown --from=guillaume betty hello
EOF

